'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import '../../public/css/woocommerce.css';
import '../../public/css/bootstrap.min.css';
import '../../public/css/custom-bootstrap.css';
import '../../public/css/custom-fonts.css';
import '../../public/css/font-awesome.min.css';
import '../../public/css/owl.carousel.min.css';
import '../../public/css/header.css';
import '../../public/css/footer.css';
import '../../public/css/responsive.css';
import '../../public/css/style.css';
import { Providers } from "@/redux/provider";
import { PriceFilterProvider } from "@/context/PriceFilterContext"; // Adjust the import path if necessary

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "OMO Fresh Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <PriceFilterProvider>
            {children}
          </PriceFilterProvider>
        </Providers>
      </body>
    </html>
  );
}
